version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build: ./shared/libs/prisma
    env_file:
      - .env
    environment:
      DB_HOST: 5555
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    env_file:
      - .env
    ports:
      - 5555:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: prisma-migrate-postgres