version: '3.8'
services:
  gateway:
    build: ./apps/gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "2222:2222"
    networks:
      - backend
  auth:
    build: ./apps/auth
    restart: always
    hostname: auth
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "./db/data/db-files:/var/lib/postgresql/data"
    ports:
      - 5440:5432
    networks:
      - backend
  prisma:
    build: ./shared/libs/prisma
    restart: always
    hostname: prisma
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - postgres
networks:
  backend:
    driver: bridge
volumes:
  postgres:
    name: nest-db