version: '3.8'
services:
  gateway:
    build: ./apps/gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "2222:2222"
    networks:
      - backend
  auth:
    build: ./apps/auth
    restart: always
    hostname: auth
    env_file:
      - .env
    networks:
      - backend
  mailer:
    build: ./apps/mailer
    restart: always
    hostname: mailer
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    driver: bridge
